### ISSUE TITLE
Update screenshots with live site images

### ISSUE THREAD

**Issue by kevinbowen777** [kevinbowen777/learning-log#58]

**Comment by Pathholder1806** [comment]
Hey! I am interested to contribute to this issue!

**Comment by Pathholder1806** [comment]
I just wanted a brief follow-up to understand the work better and resolve some doubts!

**Comment by kevinbowen777** [comment]
Hello.
Thank you for your interest. These repositories are basically just used, by me, as training exercises to teach myself Django. What doubts do you have regarding the project?

Is there something that could be made clearer in the README?

As these Django repos of mine are mostly training/demo projects, I'm not sure that you will get much contributing here. That being said, if you have a specific issue/fix, you are welcome to submit a PR. Or, feel free to fork the repo and use it for whatever you wish.

Thanks again! Have  a good day.
